#######
# Compiled from data/core/functions/main.mcscript
# to .//data/core/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say value1
say value2
say value3
say value4
say value5